# Generated by Django 6.0 on 2025-12-04 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location_lat", models.FloatField()),
                ("current_location_lng", models.FloatField()),
                ("pickup_location_lat", models.FloatField()),
                ("pickup_location_lng", models.FloatField()),
                ("dropoff_location_lat", models.FloatField()),
                ("dropoff_location_lng", models.FloatField()),
                (
                    "current_cycle_used_hours",
                    models.FloatField(
                        help_text="Hours used in current 70-hour cycle",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("polyline", models.TextField(help_text="Encoded polyline string")),
                (
                    "distance_miles",
                    models.FloatField(help_text="Total distance in miles"),
                ),
                (
                    "duration_hours",
                    models.FloatField(help_text="Total driving duration in hours"),
                ),
                (
                    "segments",
                    models.JSONField(
                        default=list,
                        help_text="Route segments with geometry and instructions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRIVING", "Driving"),
                            ("OFF_DUTY", "Off Duty"),
                            ("ON_DUTY", "On Duty"),
                            ("SLEEPER", "Sleeper Berth"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_events",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["trip", "start_time"],
                        name="trips_timel_trip_id_9ba971_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("BREAK", "Break"),
                            ("FUEL", "Fuel Stop"),
                            ("REST", "Rest Stop"),
                            ("PICKUP", "Pickup"),
                            ("DROPOFF", "Dropoff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
                "indexes": [
                    models.Index(
                        fields=["trip", "time"], name="trips_stop_trip_id_602453_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date of the log sheet (YYYY-MM-DD)"),
                ),
                (
                    "driving_hours",
                    models.FloatField(
                        default=0, help_text="Total driving hours for this day"
                    ),
                ),
                (
                    "on_duty_hours",
                    models.FloatField(
                        default=0, help_text="Total on-duty hours for this day"
                    ),
                ),
                (
                    "segments",
                    models.JSONField(
                        default=list,
                        help_text="Segments with grid indices for this day",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["trip", "date"], name="trips_daily_trip_id_22efee_idx"
                    )
                ],
                "unique_together": {("trip", "date")},
            },
        ),
    ]
