# Generated by Django 6.0 on 2025-12-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="Latitude coordinate for map display", null=True
            ),
        ),
        migrations.AddField(
            model_name="stop",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="Longitude coordinate for map display", null=True
            ),
        ),
    ]
